### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WoollenPanda275** [HimbeersaftLP/HideCommands#8] opened 2020-12-01 12:40 UTC
[12:39:04] [Server thread/ERROR]: Could not load 'C:\Users\Ajayk\OneDrive\Desktop\svr\plugins\HideCommands.phar' in folder 'C:\Users\Ajayk\OneDrive\Desktop\svr\plugins\': Unknown permission default name "fals"
[12:39:04] [Server thread/CRITICAL]: InvalidArgumentException: "Unknown permission default name "fals"" (EXCEPTION) in "src/pocketmine/permission/Permission" at line 82
[12:39:04] [Server thread/CRITICAL]: #0 src/pocketmine/permission/Permission(111): pocketmine\permission\Permission::getByName(string[4] fals)
[12:39:04] [Server thread/CRITICAL]: #1 src/pocketmine/permission/Permission(118): pocketmine\permission\Permission::loadPermission(string[19] hidecommands.unhide, array[2], string[5] false, array[0])
[12:39:04] [Server thread/CRITICAL]: #2 src/pocketmine/permission/Permission(94): pocketmine\permission\Permission::loadPermission(string[12] hidecommands, array[2], string[5] false, array[0])
[12:39:04] [Server thread/CRITICAL]: #3 src/pocketmine/plugin/PluginDescription(168): pocketmine\permission\Permission::loadPermissions(array[1])
[12:39:04] [Server thread/CRITICAL]: #4 src/pocketmine/plugin/PluginDescription(95): pocketmine\plugin\PluginDescription->loadMap(array[9])
[12:39:04] [Server thread/CRITICAL]: #5 src/pocketmine/plugin/PharPluginLoader(60): pocketmine\plugin\PluginDescription->__construct(string[415] ---.name: HideCommands.version: 1.0.3.main: Himbeer\HideCommands\Main.api:.- 3.6)
[12:39:04] [Server thread/CRITICAL]: #6 src/pocketmine/plugin/PluginManager(238): pocketmine\plugin\PharPluginLoader->getPluginDescription(string[61] C:\Users\Ajayk\OneDrive\Desktop\svr\plugins\HideCommands.phar)
[12:39:04] [Server thread/CRITICAL]: #7 src/pocketmine/Server(1854): pocketmine\plugin\PluginManager->loadPlugins(string[44] C:\Users\Ajayk\OneDrive\Desktop\svr\plugins\)
[12:39:04] [Server thread/CRITICAL]: #8 src/pocketmine/command/defaults/ReloadCommand(49): pocketmine\Server->reload()
[12:39:04] [Server thread/CRITICAL]: #9 src/pocketmine/command/SimpleCommandMap(248): pocketmine\command\defaults\ReloadCommand->execute(object pocketmine\command\ConsoleCommandSender, string[6] reload, array[0])
[12:39:04] [Server thread/CRITICAL]: #10 src/pocketmine/Server(1811): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\command\ConsoleCommandSender, string[6] reload)
[12:39:04] [Server thread/CRITICAL]: #11 src/pocketmine/Server(1423): pocketmine\Server->dispatchCommand(object pocketmine\command\ConsoleCommandSender, string[6] reload)
[12:39:04] [Server thread/CRITICAL]: #12 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\Server->pocketmine\{closure}()
[12:39:04] [Server thread/CRITICAL]: #13 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
[12:39:04] [Server thread/CRITICAL]: #14 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1606826344.125)
[12:39:04] [Server thread/CRITICAL]: #15 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
[12:39:04] [Server thread/CRITICAL]: #16 src/pocketmine/Server(1588): pocketmine\Server->start()
[12:39:04] [Server thread/CRITICAL]: #17 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[36] C:\Users\Ajayk\OneDrive\Desktop\svr\, string[44] C:\Users\Ajayk\OneDrive\Desktop\svr\plugins\)
[12:39:04] [Server thread/CRITICAL]: #18 src/pocketmine/PocketMine(304): pocketmine\server()
[12:39:04] [Server thread/CRITICAL]: #19 (11): require(string[91] phar://C:/Users/Ajayk/OneDrive/Desktop/svr/PocketMine-MP.phar/src/pocketmine/Poc)

**Comment by HimbeersaftLP** [comment] 2020-12-01 19:22
Did you modify any of the plugin's files?

**Comment by HimbeersaftLP** [comment] 2021-04-08 10:32
Closing because no details and I can't reproduce

**Closed by HimbeersaftLP** 2021-04-08 10:32 UTC
